### ISSUE TITLE
Init (Reset) function using wrong syntax

### ISSUE THREAD

**Issue by deldrid1** [electricimp/Si702x#3]
Something seems to be off with this library...  The init() function doesn't work at all (bad syntax to i2c.write()), and I get continual "reading timed out" errors when connected to a SI2071.

This code on the other hand (slightly modified for my HW setup) works just fine: https://github.com/MakeDeck/C3V0-Plus/blob/master/device.nut

**Comment by betzrhodes** [comment]
Yes this looks like a bug in the code. In the init method the i2c.write should only have 2 parameters however it is getting 3, so it will not work. Adding a task to fix this. Thanks.

**Comment by deldrid1** [comment]
FYI - turns out the reading timeouts were because I had my pin mapping wrong (looking at outdated schematics). The code does work, just not that function

**Comment by betzrhodes** [comment]
init method is fixed in v2.0.0
